#!/usr/bin/env python3
"""Minimal credential-injecting HTTPS forward proxy for QAMC.

Purpose: let the qamc trading/API process hold only inert placeholder
values for OPENROUTER_API_KEY / ALPACA_API_KEY / ALPACA_SECRET_KEY /
FRED_API_KEY, while this proxy — running under a separate, dedicated
system account that qamc and dev cannot read — substitutes the real
credential into each outbound request at the network layer.

Architecture note (see ../../docs/architecture/CREDENTIAL_PROXY.md):
this exists instead of installing the OneCLI product directly. OneCLI's
own install script (fetched and inspected, not assumed) unconditionally
requires Docker + Docker Compose + PostgreSQL + a Next.js dashboard for
what this deployment needs as exactly one property: "the real value
never touches qamc's or dev's disk/env as a live secret". That property
was empirically validated (see docs/architecture/CREDENTIAL_PROXY.md)
against QAMC's actual HTTP stacks (httpx/requests/urllib) using this
same proxy design, so implementing the pattern directly — stdlib-only,
no new services, no new dependencies — is the simpler architecture that
still achieves the goal. This file IS effectively that adopted pattern,
production-shaped rather than a disposable test harness.

Security invariants:
- Binds to 127.0.0.1 ONLY. Never call with a public bind address.
- Never logs a secret value. Logs host/path/method/status only.
- Secrets file is read once at startup and kept in memory; the file
  itself must be chmod 600, owned solely by the account running this;
  the proxy REFUSES TO START if it isn't (fail closed, not warn-only).
- Every CONNECT must present the shared Proxy-Authorization token
  configured in routes.json's "_proxy_auth_token" — loopback-only
  binding is not sufficient authentication by itself, since any other
  local account (including `dev`) can also reach 127.0.0.1. Without
  this check, a caller with no credential at all would get the same
  injected-real-secret effect as `qamc` — closing that gap is the
  entire point of this file, so it is not optional.
- TLS to the real upstream (openrouter.ai, paper-api.alpaca.markets,
  data.alpaca.markets, api.stlouisfed.org) is verified against the
  normal system/certifi CA store — this proxy does NOT weaken outbound
  certificate verification, only intercepts the LOCAL leg between the
  qamc process and this proxy (which qamc is configured to trust via a
  purpose-generated local CA, distinct from any public CA).
"""
from __future__ import annotations

import base64
import hmac
import json
import logging
import os
import socket
import ssl
import subprocess
import sys
import threading
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    stream=sys.stderr,
)
log = logging.getLogger("credential-proxy")

CONFIG_PATH = Path(os.environ.get("CREDPROXY_CONFIG", "/etc/credential-proxy/routes.json"))
CA_DIR = Path(os.environ.get("CREDPROXY_CA_DIR", "/etc/credential-proxy/ca"))
CA_CERT = CA_DIR / "ca-cert.pem"
CA_KEY = CA_DIR / "ca-key.pem"
LEAF_CACHE_DIR = CA_DIR / "leaf-cache"
BIND_HOST = "127.0.0.1"  # never anything else
BIND_PORT = int(os.environ.get("CREDPROXY_PORT", "10255"))


def load_routes() -> dict:
    """routes.json shape:
    {
      "openrouter.ai": {"upstream_port": 443, "rules": [
        {"type": "header", "name": "Authorization", "secret": "OPENROUTER_API_KEY", "format": "Bearer {value}"}
      ]},
      "paper-api.alpaca.markets": {"upstream_port": 443, "rules": [
        {"type": "header", "name": "APCA-API-KEY-ID", "secret": "ALPACA_API_KEY"},
        {"type": "header", "name": "APCA-API-SECRET-KEY", "secret": "ALPACA_SECRET_KEY"}
      ]},
      "data.alpaca.markets": {"upstream_port": 443, "rules": [ ... same two ... ]},
      "api.stlouisfed.org": {"upstream_port": 443, "rules": [
        {"type": "query_param", "name": "api_key", "secret": "FRED_API_KEY"}
      ]},
      "_secrets": {"OPENROUTER_API_KEY": "sk-or-real-...", "ALPACA_API_KEY": "...", ...},
      "_proxy_auth_token": "<random-shared-secret, generated by setup.sh>"
    }
    The whole file must be chmod 600 — it contains real secret values
    under "_secrets". Routing rules and secret values are deliberately
    kept in one file: whoever can read one already needs to be trusted
    with the other, so splitting them adds no real isolation, only
    operational complexity.

    Both the missing-file case AND the wrong-permission case are fatal
    (sys.exit), not a warning — this file is the one thing this whole
    design exists to protect, so it fails closed like the routing table
    itself does for an unconfigured host.
    """
    if not CONFIG_PATH.exists():
        log.error("Config not found at %s — refusing to start with no routes.", CONFIG_PATH)
        sys.exit(1)
    st = CONFIG_PATH.stat()
    if st.st_mode & 0o077:
        log.error(
            "Config file %s is readable by group/other (mode %o) — contains real "
            "secrets, refusing to start until it is chmod 600.",
            CONFIG_PATH, st.st_mode & 0o777,
        )
        sys.exit(1)
    with open(CONFIG_PATH) as f:
        data = json.load(f)
    if not data.get("_proxy_auth_token"):
        log.error(
            "No _proxy_auth_token configured in %s — refusing to start. Without "
            "it, any local process (including `dev`) could use this proxy exactly "
            "as if it held the real credentials.", CONFIG_PATH,
        )
        sys.exit(1)
    return data


ROUTES = load_routes()
SECRETS = ROUTES.get("_secrets", {})
AUTH_TOKEN = ROUTES["_proxy_auth_token"]


def check_proxy_auth(raw_request: bytes) -> bool:
    """Verify the CONNECT request carries the correct Proxy-Authorization.
    Accepts Basic auth (any username, password == AUTH_TOKEN) since that's
    what `HTTPS_PROXY=http://user:TOKEN@127.0.0.1:PORT` produces automatically
    in requests/httpx/urllib without any QAMC code change. Uses a
    constant-time comparison — this token is the only thing standing
    between a local process and full use of the real credentials."""
    for line in raw_request.split(b"\r\n"):
        if line.lower().startswith(b"proxy-authorization:"):
            value = line.split(b":", 1)[1].strip()
            if value.lower().startswith(b"basic "):
                try:
                    decoded = base64.b64decode(value[6:]).decode()
                except Exception:
                    return False
                _, _, password = decoded.partition(":")
                return hmac.compare_digest(password, AUTH_TOKEN)
            if value.lower().startswith(b"bearer "):
                return hmac.compare_digest(value[7:].decode(errors="replace"), AUTH_TOKEN)
    return False


def get_or_make_leaf_cert(hostname: str) -> tuple[str, str]:
    """Return (cert_path, key_path) for hostname, generating and caching
    a leaf cert signed by our local CA on first use. Shells out to
    openssl rather than adding a cryptography-library dependency —
    openssl(1) is already present on every target here."""
    LEAF_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    safe = hostname.replace("*", "_wildcard_")
    cert_path = LEAF_CACHE_DIR / f"{safe}.crt"
    key_path = LEAF_CACHE_DIR / f"{safe}.key"
    if cert_path.exists() and key_path.exists():
        return str(cert_path), str(key_path)

    csr_path = LEAF_CACHE_DIR / f"{safe}.csr"
    ext_path = LEAF_CACHE_DIR / f"{safe}.ext"
    ext_path.write_text(f"subjectAltName=DNS:{hostname}\n")

    subprocess.run(
        ["openssl", "req", "-newkey", "rsa:2048", "-keyout", str(key_path),
         "-out", str(csr_path), "-nodes", "-subj", f"/CN={hostname}"],
        check=True, capture_output=True,
    )
    subprocess.run(
        ["openssl", "x509", "-req", "-in", str(csr_path),
         "-CA", str(CA_CERT), "-CAkey", str(CA_KEY), "-CAcreateserial",
         "-out", str(cert_path), "-days", "825",
         "-extfile", str(ext_path)],
        check=True, capture_output=True,
    )
    log.info("Generated leaf cert for %s", hostname)
    return str(cert_path), str(key_path)


def read_headers(sock: ssl.SSLSocket) -> tuple[bytes, bytes]:
    """Read until the header terminator, and return (headers, leftover) —
    `leftover` is whatever body bytes arrived in the same recv() as the
    terminator (routine: nothing requires a client to send headers and
    body in separate writes). Callers MUST forward `leftover` to the
    upstream themselves before relying on any further read from this
    socket, or request bodies silently corrupt/hang — this was BLOCKER-1
    in independent review: reading `Content-Length` bytes *again* after
    already having consumed some of them here double-counted and stalled."""
    buf = b""
    while b"\r\n\r\n" not in buf:
        chunk = sock.recv(4096)
        if not chunk:
            break
        buf += chunk
        if len(buf) > 1_000_000:
            raise ValueError("request header too large")
    headers, sep, leftover = buf.partition(b"\r\n\r\n")
    return headers + sep, leftover


def rewrite_request(raw_headers: bytes, route: dict) -> bytes:
    lines = raw_headers.split(b"\r\n")
    method, path, proto = lines[0].decode().split(" ", 2)

    for rule in route.get("rules", []):
        secret_name = rule["secret"]
        real_value = SECRETS.get(secret_name)
        if real_value is None:
            log.warning("Secret %s not configured — request will proceed with client's original value.", secret_name)
            continue
        if rule["type"] == "query_param":
            name = rule["name"]
            base, _, qs = path.partition("?")
            params = [p for p in qs.split("&") if p and not p.startswith(f"{name}=")]
            params.append(f"{name}={real_value}")
            path = base + "?" + "&".join(params)

    new_lines = [f"{method} {path} {proto}".encode()]
    header_rules = {
        r["name"]: r for r in route.get("rules", []) if r["type"] == "header"
    }
    seen = set()
    for line in lines[1:]:
        if not line:
            continue
        hname = line.split(b":", 1)[0].decode().strip() if b":" in line else None
        if hname in header_rules:
            rule = header_rules[hname]
            real_value = SECRETS.get(rule["secret"])
            if real_value is not None:
                fmt = rule.get("format", "{value}")
                new_lines.append(f"{hname}: {fmt.format(value=real_value)}".encode())
                seen.add(hname)
                continue
        new_lines.append(line)
    for hname, rule in header_rules.items():
        if hname not in seen and SECRETS.get(rule["secret"]) is not None:
            fmt = rule.get("format", "{value}")
            new_lines.append(f"{hname}: {fmt.format(value=SECRETS[rule['secret']])}".encode())
    new_lines.append(b"")
    new_lines.append(b"")
    return b"\r\n".join(new_lines), method, path


def pump(src, dst, label):
    try:
        while True:
            chunk = src.recv(65536)
            if not chunk:
                break
            dst.sendall(chunk)
    except Exception as e:
        log.debug("pump[%s] ended: %r", label, e)
    finally:
        try:
            dst.shutdown(socket.SHUT_WR)
        except Exception:
            pass


def handle_client(client_sock: socket.socket, addr) -> None:
    host = None
    try:
        raw = b""
        while b"\r\n\r\n" not in raw:
            chunk = client_sock.recv(4096)
            if not chunk:
                client_sock.close()
                return
            raw += chunk
        first_line = raw.split(b"\r\n")[0].decode()
        if not first_line.startswith("CONNECT"):
            client_sock.sendall(b"HTTP/1.1 400 Bad Request\r\n\r\n")
            client_sock.close()
            return

        if not check_proxy_auth(raw):
            log.warning("CONNECT from %s missing/wrong Proxy-Authorization — refusing.", addr)
            client_sock.sendall(b'HTTP/1.1 407 Proxy Authentication Required\r\nProxy-Authenticate: Basic realm="credential-proxy"\r\n\r\n')
            client_sock.close()
            return

        target = first_line.split(" ")[1]
        host, _, _requested_port = target.partition(":")
        # The client-requested port is deliberately ignored — the upstream
        # connection below always uses routes.json's configured
        # upstream_port, not whatever port a CONNECT line asks for. This
        # stops a caller from reusing an allow-listed hostname to reach a
        # different port on that same host.

        route = ROUTES.get(host)
        if route is None:
            log.warning("CONNECT to unconfigured host %s — refusing (no route).", host)
            client_sock.sendall(b"HTTP/1.1 403 Forbidden\r\n\r\n")
            client_sock.close()
            return

        client_sock.sendall(b"HTTP/1.1 200 Connection Established\r\n\r\n")

        leaf_cert, leaf_key = get_or_make_leaf_cert(host)
        server_ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        server_ctx.load_cert_chain(certfile=leaf_cert, keyfile=leaf_key)
        tls_client = server_ctx.wrap_socket(client_sock, server_side=True)

        raw_headers, leftover_body = read_headers(tls_client)
        if not raw_headers:
            tls_client.close()
            return

        rewritten, method, path = rewrite_request(raw_headers, route)
        log.info("%s %s%s -> injected %d rule(s)", method, host, path.split("?")[0], len(route.get("rules", [])))

        # CREDPROXY_TEST_UPSTREAM_CA is a TEST-ONLY escape hatch (unset in every
        # real deployment) so integration tests can point the upstream leg at a
        # local mock server without weakening production's real public-CA trust.
        test_ca = os.environ.get("CREDPROXY_TEST_UPSTREAM_CA")
        upstream_ctx = ssl.create_default_context(cafile=test_ca) if test_ca else ssl.create_default_context()
        raw_upstream = socket.create_connection((host, route.get("upstream_port", 443)), timeout=30)
        tls_upstream = upstream_ctx.wrap_socket(raw_upstream, server_hostname=host)
        tls_upstream.sendall(rewritten)

        # Forward any body bytes that arrived bundled with the header read
        # BEFORE starting the generic pump — otherwise those bytes are lost
        # and the two sides fall out of sync (BLOCKER-1 in independent review).
        if leftover_body:
            tls_upstream.sendall(leftover_body)

        # No manual Content-Length-bounded read: the client->upstream pump
        # below carries the rest of any body (fixed-length, chunked, or
        # none) exactly as-is, since it doesn't need to understand HTTP
        # framing — it just relays bytes until the client shuts its write
        # side, which is correct for all three cases and impossible to get
        # out of sync with, unlike manually counting bytes.
        t1 = threading.Thread(target=pump, args=(tls_upstream, tls_client, f"{host}<-up"), daemon=True)
        t2 = threading.Thread(target=pump, args=(tls_client, tls_upstream, f"{host}->up"), daemon=True)
        t1.start(); t2.start()
        t1.join(); t2.join()
        tls_client.close()
        tls_upstream.close()
    except Exception as e:
        log.warning("error handling %s (host=%s): %r", addr, host, e)


def main():
    listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    listener.bind((BIND_HOST, BIND_PORT))
    listener.listen(16)
    log.info("credential-proxy listening on http://%s:%d (CONNECT-based, %d routes configured)",
              BIND_HOST, BIND_PORT, len([k for k in ROUTES if not k.startswith("_")]))
    while True:
        client_sock, addr = listener.accept()
        threading.Thread(target=handle_client, args=(client_sock, addr), daemon=True).start()


if __name__ == "__main__":
    main()
