"""FastAPI app wiring for the Mission Control API.

This module owns the ONLY place the two route modules are assembled into a
running app. It also mounts the Stage 3 cockpit (`src/api/static/`) — a
static HTML/CSS/JS bundle with no build step and no server-side rendering,
so it carries none of the read/write risk the JSON routes below are guarded
against; it only ever calls this same GET-only API from the browser. It
adds two structural, app-level safety guarantees on top of what each router
already does individually:

1. **GET-only enforcement, at the app level.** A middleware rejects any
   request whose method is not GET/HEAD/OPTIONS with 405 before it can reach
   ANY route — even a future route added carelessly to `routes_live.py` /
   `routes_history.py` without a matching safety test would still be
   incapable of accepting a write. This is belt-and-suspenders on top of the
   fact that neither router registers anything but `@router.get(...)`.
2. **A global exception handler.** Any unhandled exception anywhere below
   this app (a genuine bug, a corrupted DB file, whatever) becomes a plain
   `{"detail": "internal error"}` 500 — never a raw traceback, which could
   leak file paths or other internals. This is what "malformed/read
   failures fail at the API boundary" (Stage 2 Checkpoint C) means in
   practice: the API process itself stays up and answers a clean error.

Nothing in this file, `routes_live.py`, `routes_history.py`, `broker_reads.py`,
or `db_reads.py` imports `src.pipeline`, `src.pipeline_stages`,
`src.risk.*`, or any write-capable method of `src.execution.broker` /
`src.storage.db`. That is the Stage 2 isolation invariant, verified by
`tests/test_api_isolation.py`.
"""

from __future__ import annotations

import logging
import re
import subprocess
from pathlib import Path

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from starlette.middleware.base import BaseHTTPMiddleware

from src.api.routes_evidence import router as evidence_router
from src.api.routes_history import router as history_router
from src.api.routes_journal import router as journal_router
from src.api.routes_live import router as live_router
from src.api.routes_research import router as research_router

_STATIC_DIR = Path(__file__).parent / "static"
# Stage 6 — the richer cockpit (docs/visual/MISSION_CONTROL_VISION_BOARD.png
# as layout/hierarchy reference). A second, independent static bundle, not
# a replacement: /ui keeps serving the Stage 3-5 dashboard byte-for-byte as
# a safe fallback while this one is verified. Same no-build-step, no-
# framework, no-new-dependency posture — see docs/WORK.md's explicit
# "no framework migration without architecture approval" boundary.
_COCKPIT_DIR = Path(__file__).parent / "static_cockpit"

# Generated by `scripts/status_board.py` on a timer, never committed: `data/`
# is gitignored precisely so machine-written files cannot become deploy drift.
_BOARD_DIR = Path(__file__).resolve().parents[2] / "data" / "board"
_BOARD_FILE = _BOARD_DIR / "index.html"

# Same production checkout `scripts/status_board.py` reads its own "box_sha"
# from (see PROD_CHECKOUT there). Duplicated as a plain constant rather than
# imported: `scripts/` depends on `src/`, not the other way around, and this
# is one path, not a library to share.
_PROD_CHECKOUT = Path("/home/qamc/quant-agent")

#: Pulls the board's build-time SHA back out of the <meta> tag
#: `scripts/status_board.py` stamps into the page it generates.
_BUILT_SHA_RE = re.compile(r'<meta name="qamc-board-built-sha" content="([0-9a-fA-F]*)"')

logger = logging.getLogger(__name__)

_SAFE_METHODS = {"GET", "HEAD", "OPTIONS"}


class _GetOnlyMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        if request.method not in _SAFE_METHODS:
            return JSONResponse(
                status_code=405,
                content={"detail": "Mission Control API is read-only: GET only"},
            )
        return await call_next(request)


# --------------------------------------------------------------------------
# /board — served by hand, not StaticFiles, so freshness can be checked
# against a fact (the running commit) instead of a clock. See
# `scripts/status_board.py`'s module docstring: this board would rather say
# "unknown" than say something false, and a time-based staleness banner
# cannot honour that — a quiet weekend legitimately produces an old page
# with nothing wrong. The one thing that DOES mean something moved on is the
# page's build-time commit no longer matching the commit running right now.
# --------------------------------------------------------------------------

def _board_live_sha() -> str | None:
    """Read the commit the production box is running, right now.

    Mirrors `_prod_git("rev-parse", "HEAD")` in scripts/status_board.py: a
    direct git read first (works when this process itself runs as `qamc`),
    falling back to the same passwordless-sudo path the board relies on.
    Never raises. Returns None — never a guess — if neither works, so the
    caller reports the freshness as unknown rather than implying it's fine.
    """
    for cmd in (
        ["git", "-C", str(_PROD_CHECKOUT), "rev-parse", "HEAD"],
        ["sudo", "-n", "-u", "qamc", "git", "-C", str(_PROD_CHECKOUT), "rev-parse", "HEAD"],
    ):
        try:
            p = subprocess.run(cmd, capture_output=True, text=True, timeout=5)
        except Exception:  # noqa: BLE001 - a broken probe must not break the page
            continue
        sha = p.stdout.strip()
        if p.returncode == 0 and sha:
            return sha
    return None


def _board_built_sha(board_html: str) -> str | None:
    """Pull the version the board was generated from out of its own markup.

    None if the page carries no stamp at all (an older page, or the box's
    SHA was unreadable at build time) — never an empty-string stand-in that
    could accidentally compare equal to something.
    """
    m = _BUILT_SHA_RE.search(board_html)
    if not m or not m.group(1):
        return None
    return m.group(1)


def _freshness_banner(built_sha: str | None, live_sha: str | None) -> str:
    """A prominent banner to inject at the top of the page, or "" for none.

    Three outcomes, and only three:
      - both known and equal   -> "" (say nothing; the page is current)
      - both known and unequal -> a plain "this has changed" banner
      - either side unknown    -> a plain "freshness UNKNOWN" banner

    Reuses the page's own --crit / --crit-bg variables via the existing
    `.stale` class already defined in scripts/status_board_template.html —
    no new colours, no script; the decision is made here, server-side,
    before the page is ever sent.
    """
    if not built_sha or not live_sha:
        return (
            '<div class="stale"><b>Board freshness: UNKNOWN.</b> '
            "This page's build version could not be compared against the "
            "system currently running, so there is no way to confirm "
            "whether it is up to date.</div>"
        )
    if built_sha != live_sha:
        return (
            '<div class="stale"><b>This board is out of date.</b> '
            f"It was built from commit {built_sha[:9]}, but the system is "
            f"now running {live_sha[:9]}. The system has changed since this "
            "board was built &mdash; treat what follows as a snapshot, not "
            "current state.</div>"
        )
    return ""


def _inject_banner(board_html: str, banner: str) -> str:
    """Place the banner right at the top of the visible page. No-op for "".

    `<div class="wrap">` is the page's own outer container — present in
    every board the template produces — so this needs no coordination with
    `scripts/status_board.py` beyond that container existing.
    """
    if not banner:
        return board_html
    marker = '<div class="wrap">'
    idx = board_html.find(marker)
    if idx == -1:
        return banner + board_html
    at = idx + len(marker)
    return board_html[:at] + banner + board_html[at:]


def _render_board() -> HTMLResponse:
    if not _BOARD_FILE.is_file():
        return HTMLResponse(
            "<p>The status board has not been generated yet. It is written "
            "by <code>scripts/status_board.py</code>, run on a timer — "
            "check back shortly.</p>",
            status_code=200,
        )
    board_html = _BOARD_FILE.read_text()
    banner = _freshness_banner(_board_built_sha(board_html), _board_live_sha())
    return HTMLResponse(_inject_banner(board_html, banner))


def create_app() -> FastAPI:
    app = FastAPI(
        title="QAMC Mission Control API",
        description=(
            "Stage 2 — thin, read-only adapter over quant-agent's existing "
            "canonical state. Never places, cancels, or modifies broker "
            "orders; never calls an AI agent or the Portfolio Manager; "
            "trading runs unaffected by this process's presence or absence."
        ),
        version="0.1.0",
    )
    app.add_middleware(_GetOnlyMiddleware)
    app.include_router(live_router, tags=["live"])
    app.include_router(history_router, tags=["history"])
    app.include_router(evidence_router, tags=["evidence"])
    app.include_router(journal_router, tags=["journal"])
    app.include_router(research_router, tags=["research"])

    if _STATIC_DIR.is_dir():
        # Stage 3 cockpit — static assets only, no templating/server state.
        # Mounted last and under its own path so it never shadows the JSON
        # routes above or the `/` service-meta route below.
        app.mount("/ui", StaticFiles(directory=str(_STATIC_DIR), html=True), name="ui")

    if _COCKPIT_DIR.is_dir():
        # Stage 6 cockpit — same static-assets-only posture as /ui above.
        app.mount("/cockpit", StaticFiles(directory=str(_COCKPIT_DIR), html=True), name="cockpit")

    # The human status board (`scripts/status_board.py`, run on a timer). It
    # lives under `data/`, which is gitignored, so regenerating it can never
    # dirty the production checkout — the deploy-drift problem that cost a
    # day on 2026-08-28 started exactly that way, with a file the box edited
    # that git also tracked. Unlike /ui and /cockpit above this is a small
    # handler, not a StaticFiles mount: it has to compare the page's built-
    # from commit against the commit running right now on every request (see
    # `_render_board` above), and it has to keep answering — with a plain
    # message, not a 404/stack trace — even before the board has ever been
    # generated, which StaticFiles cannot do. Read-only either way; the
    # GET-only middleware still covers it.
    @app.get("/board", include_in_schema=False)
    @app.get("/board/", include_in_schema=False)
    def board() -> HTMLResponse:
        return _render_board()

    @app.exception_handler(Exception)
    async def _unhandled_exception_handler(request: Request, exc: Exception):
        logger.warning("Unhandled exception on %s %s: %s", request.method, request.url.path, exc)
        return JSONResponse(status_code=500, content={"detail": "internal error"})

    @app.get("/", tags=["meta"])
    def root() -> dict:
        return {"service": "qamc-mission-control-api", "status": "ok"}

    return app


app = create_app()
